enum DeliveryStatus {
  AWAITING_PROCESSING = "AWAITING_PROCESSING",
  PROCESSING = "PROCESSING",
  SHIPPED = "SHIPPED",
  DELIVERED = "DELIVERED",
  NOT_DELIVERED = "NOT_DELIVERED",
  CANCELED = "CANCELED",
}

export default DeliveryStatus;
